"""add actual_mirror and reconciliation fields

Revision ID: 08f68727bcf7
Revises: 36bda4cfb4b2
Create Date: 2026-07-02 18:39:52.885841
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '08f68727bcf7'
down_revision: Union[str, None] = '36bda4cfb4b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actual_mirror',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actual_txn_id', sa.String(), nullable=False),
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('payee_name', sa.String(), nullable=True),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.Column('imported_id', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_parent', sa.Boolean(), nullable=False),
    sa.Column('transfer_id', sa.String(), nullable=True),
    sa.Column('refreshed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actual_mirror', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actual_mirror_account_name'), ['account_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_actual_mirror_actual_txn_id'), ['actual_txn_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_actual_mirror_amount_cents'), ['amount_cents'], unique=False)
        batch_op.create_index(batch_op.f('ix_actual_mirror_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_actual_mirror_imported_id'), ['imported_id'], unique=False)
        batch_op.create_index('ix_mirror_match', ['account_name', 'amount_cents', 'date'], unique=False)

    # NOTA: el autogenerate quería borrar ix_transaction_splits_txn_id (existe en la
    # migración de splits pero el modelo no lo declara). Falso positivo: NO se borra.

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sync_origin', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('match_candidate_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('match_tier', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_transactions_match_candidate', 'actual_mirror', ['match_candidate_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transactions_match_candidate', type_='foreignkey')
        batch_op.drop_column('match_tier')
        batch_op.drop_column('match_candidate_id')
        batch_op.drop_column('sync_origin')

    with op.batch_alter_table('actual_mirror', schema=None) as batch_op:
        batch_op.drop_index('ix_mirror_match')
        batch_op.drop_index(batch_op.f('ix_actual_mirror_imported_id'))
        batch_op.drop_index(batch_op.f('ix_actual_mirror_date'))
        batch_op.drop_index(batch_op.f('ix_actual_mirror_amount_cents'))
        batch_op.drop_index(batch_op.f('ix_actual_mirror_actual_txn_id'))
        batch_op.drop_index(batch_op.f('ix_actual_mirror_account_name'))

    op.drop_table('actual_mirror')
    # ### end Alembic commands ###
