"""add csv_mappings

Revision ID: 384f2fb45f6c
Revises: a7055be83c09
Create Date: 2026-07-02 12:47:39.716721
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '384f2fb45f6c'
down_revision: Union[str, None] = 'a7055be83c09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csv_mappings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('header_signature', sa.String(), nullable=False),
    sa.Column('source_bank', sa.String(), nullable=False),
    sa.Column('source_account', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('delimiter', sa.String(), nullable=False),
    sa.Column('colmap_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('csv_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_csv_mappings_header_signature'), ['header_signature'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('csv_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_csv_mappings_header_signature'))

    op.drop_table('csv_mappings')
    # ### end Alembic commands ###
