"""add pending column

Revision ID: a7055be83c09
Revises: c05b23266349
Create Date: 2026-07-02 11:19:21.544191
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a7055be83c09'
down_revision: Union[str, None] = 'c05b23266349'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # server_default para que las filas ya existentes tomen False al agregar la columna NOT NULL.
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending', sa.Boolean(), nullable=False, server_default=sa.false()))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('pending')

    # ### end Alembic commands ###
