"""initial schema

Revision ID: c05b23266349
Revises: 
Create Date: 2026-07-02 10:56:49.728431
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c05b23266349'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('schema_version', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('open', 'approved', 'pushed', name='batchstatus'), nullable=False),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source_bank', sa.String(), nullable=False),
    sa.Column('source_file', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('raw_file_path', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('received', 'parsed', 'failed', name='importstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('imports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_imports_file_hash'), ['file_hash'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('import_id', sa.String(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=True),
    sa.Column('source_bank', sa.String(), nullable=False),
    sa.Column('source_account', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=False),
    sa.Column('source_file', sa.String(), nullable=True),
    sa.Column('source_row', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('raw_payee', sa.String(), nullable=False),
    sa.Column('payee', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('is_transfer', sa.Boolean(), nullable=False),
    sa.Column('transfer_pair_id', sa.String(), nullable=True),
    sa.Column('imported_id', sa.String(), nullable=False),
    sa.Column('dedup_hash', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('parsed', 'normalized', 'needs_review', 'approved', 'synced', 'rejected', name='txnstatus'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), nullable=False),
    sa.Column('duplicate_of', sa.String(), nullable=True),
    sa.Column('actual_txn_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['duplicate_of'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_dedup_hash'), ['dedup_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_imported_id'), ['imported_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_transactions_status'), ['status'], unique=False)
        batch_op.create_index('ix_txn_batch_status', ['batch_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_txn_batch_status')
        batch_op.drop_index(batch_op.f('ix_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_transactions_imported_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_dedup_hash'))

    op.drop_table('transactions')
    with op.batch_alter_table('imports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_imports_file_hash'))

    op.drop_table('imports')
    op.drop_table('batches')
    # ### end Alembic commands ###
