"""add app_settings

Revision ID: d3c40ae73a19
Revises: 08f68727bcf7
Create Date: 2026-07-02 19:00:13.738768
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd3c40ae73a19'
down_revision: Union[str, None] = '08f68727bcf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # (autogenerate quería borrar ix_transaction_splits_txn_id — falso positivo, no se toca)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_settings')
    # ### end Alembic commands ###
